import { FiBook, FiBarChart2 } from 'react-icons/fi';
import { FaDownload } from 'react-icons/fa6';
import { LuAlarmClock } from 'react-icons/lu';
import { useState, useMemo } from 'react';

export default function Resources() {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedType, setSelectedType] = useState('All Types');
  const [selectedLevel, setSelectedLevel] = useState('All Levels');

  const resources = [
    {
      id: 1,
      title: "Calculus Basics",
      type: "Video",
      subject: "Mathematics",
      duration: "45 min",
      difficulty: "Beginner",
      url: "https://www.youtube.com/watch?v=mRCXh__pexQ&list=PLmdFyQYShrjd4Qn42rcBeFvF6Qs-b6e-L",
    },
    {
      id: 2,
      title: "Newton's Laws of Motion",
      type: "Article",
      subject: "Physics",
      duration: "20 min read",
      difficulty: "Intermediate",
      url: "https://en.wikipedia.org/wiki/Newton%27s_laws_of_motion",
    },
    {
      id: 3,
      title: "Organic Chemistry Reactions",
      type: "Interactive",
      subject: "Chemistry",
      duration: "60 min",
      difficulty: "Intermediate",
      url: "https://interactivechemistry.org/",
    },
    {
      id: 4,
      title: "Shakespeare's Sonnets",
      type: "Document",
      subject: "English",
      duration: "30 min read",
      difficulty: "Beginner",
      url: "https://nosweatshakespeare.com/sonnets/",
    },
    // Mathematics

    // Extra Learning
    {
      id: 45,
      title: "Study Skills",
      type: "Article",
      subject: "General",
      duration: "20 min read",
      difficulty: "Beginner",
      url: "https://www.mindtools.com/pages/main/newMN_HTE.htm",
    },
    {
      id: 46,
      title: "Time Management",
      type: "Video",
      subject: "General",
      duration: "25 min",
      difficulty: "Beginner",
      url: "https://www.youtube.com/watch?v=oTugjssqOT0",
    },
    {
      id: 47,
      title: "Critical Thinking",
      type: "Article",
      subject: "General",
      duration: "30 min read",
      difficulty: "Intermediate",
      url: "https://www.skillsyouneed.com/learn/critical-thinking.html",
    },
    {
      id: 48,
      title: "Problem Solving",
      type: "Course",
      subject: "General",
      duration: "1 hr",
      difficulty: "Intermediate",
      url: "https://www.coursera.org/learn/problem-solving",
    },
    {
      id: 49,
      title: "Exam Preparation Tips",
      type: "Article",
      subject: "General",
      duration: "15 min read",
      difficulty: "Beginner",
      url: "https://www.topuniversities.com/student-info/health-and-support/exam-preparation-tips",
    },

    // More Mathematics
    {
      id: 50,
      title: "Coordinate Geometry",
      type: "Video",
      subject: "Mathematics",
      duration: "40 min",
      difficulty: "Intermediate",
      url: "https://www.khanacademy.org/math/geometry/hs-geo-analytic-geometry",
    },
    {
      id: 51,
      title: "Functions & Graphs",
      type: "Article",
      subject: "Mathematics",
      duration: "30 min read",
      difficulty: "Intermediate",
      url: "https://www.mathsisfun.com/sets/function.html",
    },
    {
      id: 52,
      title: "Limits & Continuity",
      type: "Video",
      subject: "Mathematics",
      duration: "50 min",
      difficulty: "Advanced",
      url: "https://www.khanacademy.org/math/calculus-1/cs1-limits-and-continuity",
    },
    {
      id: 53,
      title: "Matrices",
      type: "Article",
      subject: "Mathematics",
      duration: "25 min read",
      difficulty: "Intermediate",
      url: "https://www.mathsisfun.com/algebra/matrix-introduction.html",
    },
    {
      id: 54,
      title: "Differentiation",
      type: "Video",
      subject: "Mathematics",
      duration: "45 min",
      difficulty: "Advanced",
      url: "https://www.khanacademy.org/math/calculus-1/cs1-derivatives",
    },

    // Physics Continued
    {
      id: 55,
      title: "Laws of Motion Problems",
      type: "Article",
      subject: "Physics",
      duration: "30 min read",
      difficulty: "Intermediate",
      url: "https://www.physicsclassroom.com/class/newtlaws",
    },
    {
      id: 56,
      title: "Gravitation",
      type: "Video",
      subject: "Physics",
      duration: "35 min",
      difficulty: "Intermediate",
      url: "https://www.khanacademy.org/science/physics/centripetal-force-and-gravitation",
    },
    {
      id: 57,
      title: "Magnetism",
      type: "Article",
      subject: "Physics",
      duration: "25 min read",
      difficulty: "Beginner",
      url: "https://www.britannica.com/science/magnetism",
    },
    {
      id: 58,
      title: "Thermodynamics",
      type: "Video",
      subject: "Physics",
      duration: "50 min",
      difficulty: "Advanced",
      url: "https://www.khanacademy.org/science/physics/thermodynamics",
    },
    {
      id: 59,
      title: "Nuclear Physics",
      type: "Article",
      subject: "Physics",
      duration: "35 min read",
      difficulty: "Advanced",
      url: "https://www.britannica.com/science/nuclear-physics",
    },

    // Chemistry Continued
    {
      id: 60,
      title: "Atomic Structure",
      type: "Video",
      subject: "Chemistry",
      duration: "30 min",
      difficulty: "Beginner",
      url: "https://www.khanacademy.org/science/chemistry/atomic-structure-and-properties",
    },
    {
      id: 61,
      title: "Thermochemistry",
      type: "Article",
      subject: "Chemistry",
      duration: "30 min read",
      difficulty: "Intermediate",
      url: "https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry",
    },
    {
      id: 62,
      title: "Chemical Kinetics",
      type: "Video",
      subject: "Chemistry",
      duration: "40 min",
      difficulty: "Advanced",
      url: "https://www.khanacademy.org/science/chemistry/chemical-reactions-rates",
    },
    {
      id: 63,
      title: "Solutions & Solubility",
      type: "Article",
      subject: "Chemistry",
      duration: "25 min read",
      difficulty: "Intermediate",
      url: "https://www.britannica.com/science/solution-chemistry",
    },
    {
      id: 64,
      title: "Environmental Chemistry",
      type: "Video",
      subject: "Chemistry",
      duration: "35 min",
      difficulty: "Beginner",
      url: "https://www.khanacademy.org/science/ap-chemistry-beta/x2eef969c74e0d802:applications-of-chemistry",
    },

    // Biology Continued
    {
      id: 65,
      title: "Cell Division",
      type: "Video",
      subject: "Biology",
      duration: "30 min",
      difficulty: "Beginner",
      url: "https://www.khanacademy.org/science/biology/cellular-molecular-biology/mitosis-meiosis",
    },
    {
      id: 66,
      title: "Respiration",
      type: "Article",
      subject: "Biology",
      duration: "20 min read",
      difficulty: "Beginner",
      url: "https://www.britannica.com/science/cellular-respiration",
    },
    {
      id: 67,
      title: "Nervous System",
      type: "Video",
      subject: "Biology",
      duration: "40 min",
      difficulty: "Intermediate",
      url: "https://www.khanacademy.org/science/biology/human-biology/neuron-nervous-system",
    },
    {
      id: 68,
      title: "Immune System",
      type: "Article",
      subject: "Biology",
      duration: "30 min read",
      difficulty: "Intermediate",
      url: "https://www.nature.com/subjects/immune-system",
    },
    {
      id: 69,
      title: "Biotechnology",
      type: "Video",
      subject: "Biology",
      duration: "45 min",
      difficulty: "Advanced",
      url: "https://www.khanacademy.org/science/ap-biology/gene-expression-and-regulation",
    },

    // Computer Science Continued
    {
      id: 70,
      title: "Python Basics",
      type: "Course",
      subject: "Computer Science",
      duration: "2 hrs",
      difficulty: "Beginner",
      url: "https://www.freecodecamp.org/learn/scientific-computing-with-python/",
    },
    {
      id: 71,
      title: "Algorithms Intro",
      type: "Video",
      subject: "Computer Science",
      duration: "50 min",
      difficulty: "Intermediate",
      url: "https://www.khanacademy.org/computing/computer-science/algorithms",
    },
    {
      id: 72,
      title: "Git & GitHub",
      type: "Article",
      subject: "Computer Science",
      duration: "30 min read",
      difficulty: "Beginner",
      url: "https://www.atlassian.com/git/tutorials",
    },
    {
      id: 73,
      title: "APIs Explained",
      type: "Video",
      subject: "Computer Science",
      duration: "25 min",
      difficulty: "Intermediate",
      url: "https://www.youtube.com/watch?v=GZvSYJDk-us",
    },
    {
      id: 74,
      title: "Cybersecurity Basics",
      type: "Article",
      subject: "Computer Science",
      duration: "35 min read",
      difficulty: "Beginner",
      url: "https://www.cloudflare.com/learning/",
    },

    // English Continued
    {
      id: 75,
      title: "Comprehension Skills",
      type: "Article",
      subject: "English",
      duration: "20 min read",
      difficulty: "Beginner",
      url: "https://www.readingrockets.org/strategies",
    },
    {
      id: 76,
      title: "Speech Writing",
      type: "Video",
      subject: "English",
      duration: "30 min",
      difficulty: "Intermediate",
      url: "https://www.youtube.com/watch?v=Unzc731iCUY",
    },
    {
      id: 77,
      title: "Drama & Plays",
      type: "Article",
      subject: "English",
      duration: "30 min read",
      difficulty: "Intermediate",
      url: "https://www.britannica.com/art/drama-literature",
    },
    {
      id: 78,
      title: "Vocabulary Building",
      type: "Interactive",
      subject: "English",
      duration: "20 min",
      difficulty: "Beginner",
      url: "https://www.vocabulary.com/",
    },
    {
      id: 79,
      title: "Literary Devices",
      type: "Article",
      subject: "English",
      duration: "25 min read",
      difficulty: "Intermediate",
      url: "https://literarydevices.net/",
    },

    // History, Geography, Civics
    {
      id: 80,
      title: "Cold War",
      type: "Video",
      subject: "History",
      duration: "40 min",
      difficulty: "Intermediate",
      url: "https://www.khanacademy.org/humanities/world-history/euro-hist/cold-war-era",
    },
    {
      id: 81,
      title: "Industrial Revolution",
      type: "Article",
      subject: "History",
      duration: "35 min read",
      difficulty: "Beginner",
      url: "https://www.history.com/topics/industrial-revolution",
    },
    {
      id: 82,
      title: "Population Geography",
      type: "Video",
      subject: "Geography",
      duration: "30 min",
      difficulty: "Beginner",
      url: "https://www.khanacademy.org/humanities/ap-human-geography",
    },
    {
      id: 83,
      title: "Natural Resources",
      type: "Article",
      subject: "Geography",
      duration: "25 min read",
      difficulty: "Beginner",
      url: "https://www.nationalgeographic.org/encyclopedia/resource/",
    },
    {
      id: 84,
      title: "Democracy & Government",
      type: "Article",
      subject: "Civics",
      duration: "30 min read",
      difficulty: "Beginner",
      url: "https://www.britannica.com/topic/democracy",
    },

    // Economics, Business, Life Skills
    {
      id: 85,
      title: "Inflation Explained",
      type: "Video",
      subject: "Economics",
      duration: "20 min",
      difficulty: "Beginner",
      url: "https://www.khanacademy.org/economics-finance-domain/macroeconomics",
    },
    {
      id: 86,
      title: "Budgeting Basics",
      type: "Article",
      subject: "Economics",
      duration: "20 min read",
      difficulty: "Beginner",
      url: "https://www.investopedia.com/budgeting-basics-5184345",
    },
    {
      id: 87,
      title: "Personal Finance",
      type: "Course",
      subject: "Business",
      duration: "1 hr",
      difficulty: "Beginner",
      url: "https://www.khanacademy.org/college-careers-more/personal-finance",
    },
    {
      id: 88,
      title: "Leadership Skills",
      type: "Article",
      subject: "Business",
      duration: "25 min read",
      difficulty: "Intermediate",
      url: "https://www.mindtools.com/pages/main/newMN_LDR.htm",
    },
    {
      id: 89,
      title: "Public Speaking",
      type: "Video",
      subject: "Business",
      duration: "30 min",
      difficulty: "Intermediate",
      url: "https://www.youtube.com/watch?v=HAnw168huqA",
    },

    // General Skills
    {
      id: 90,
      title: "Memory Techniques",
      type: "Article",
      subject: "General",
      duration: "15 min read",
      difficulty: "Beginner",
      url: "https://www.verywellmind.com/memory-techniques-2795356",
    },
    {
      id: 91,
      title: "Note Taking Methods",
      type: "Video",
      subject: "General",
      duration: "20 min",
      difficulty: "Beginner",
      url: "https://www.youtube.com/watch?v=AffuwyJZTQQ",
    },
    {
      id: 92,
      title: "Mind Mapping",
      type: "Interactive",
      subject: "General",
      duration: "20 min",
      difficulty: "Beginner",
      url: "https://www.mindmeister.com/",
    },
    {
      id: 93,
      title: "Focus & Concentration",
      type: "Article",
      subject: "General",
      duration: "15 min read",
      difficulty: "Beginner",
      url: "https://www.healthline.com/health/how-to-improve-concentration",
    },
    {
      id: 94,
      title: "Stress Management",
      type: "Video",
      subject: "General",
      duration: "25 min",
      difficulty: "Beginner",
      url: "https://www.youtube.com/watch?v=hnpQrMqDoqE",
    },

    // Final Entries
    {
      id: 95,
      title: "Online Learning Tips",
      type: "Article",
      subject: "General",
      duration: "15 min read",
      difficulty: "Beginner",
      url: "https://www.edutopia.org/online-learning",
    },
    {
      id: 96,
      title: "Career Planning",
      type: "Video",
      subject: "General",
      duration: "30 min",
      difficulty: "Beginner",
      url: "https://www.youtube.com/watch?v=J5k8ZQsZJpk",
    },
    {
      id: 97,
      title: "Scholarship Search",
      type: "Article",
      subject: "General",
      duration: "20 min read",
      difficulty: "Beginner",
      url: "https://www.scholarships.com/",
    },
    {
      id: 98,
      title: "Resume Writing",
      type: "Article",
      subject: "General",
      duration: "25 min read",
      difficulty: "Intermediate",
      url: "https://zety.com/blog/resume-writing",
    },
    {
      id: 99,
      title: "Interview Skills",
      type: "Video",
      subject: "General",
      duration: "30 min",
      difficulty: "Intermediate",
      url: "https://www.youtube.com/watch?v=HG68Ymazo18",
    },
    {
      id: 100,
      title: "Lifelong Learning",
      type: "Article",
      subject: "General",
      duration: "15 min read",
      difficulty: "Beginner",
      url: "https://www.futurelearn.com/info/blog/what-is-lifelong-learning",
    },
    {
      id: 101,
      title: "Coursera",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.coursera.org",
    },
    {
      id: 102,
      title: "edX",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.edx.org",
    },
    {
      id: 103,
      title: "MIT OpenCourseWare",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Advanced",
      url: "https://ocw.mit.edu",
    },
    {
      id: 104,
      title: "FutureLearn",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.futurelearn.com",
    },
    {
      id: 105,
      title: "Harvard Online Learning",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Advanced",
      url: "https://online-learning.harvard.edu",
    },
    {
      id: 106,
      title: "Stanford Online",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Advanced",
      url: "https://online.stanford.edu",
    },
    {
      id: 107,
      title: "Saylor Academy",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.saylor.org",
    },
    {
      id: 108,
      title: "OpenLearn",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.open.edu/openlearn",
    },
    {
      id: 109,
      title: "Academic Earth",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://academicearth.org",
    },
    {
      id: 110,
      title: "Alison",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://alison.com",
    },
    {
      id: 111,
      title: "Khan Academy - School",
      type: "Video",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.khanacademy.org",
    },
    {
      id: 112,
      title: "CK 12 Foundation",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.ck12.org",
    },
    {
      id: 113,
      title: "BBC Bitesize",
      type: "Interactive",
      subject: "General",
      duration: "20 min",
      difficulty: "Beginner",
      url: "https://www.bbc.co.uk/bitesize",
    },
    {
      id: 114,
      title: "National Geographic Kids",
      type: "Article",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://kids.nationalgeographic.com",
    },
    {
      id: 115,
      title: "PBS Kids",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://pbskids.org",
    },
    {
      id: 116,
      title: "Funbrain",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.funbrain.com",
    },
    {
      id: 117,
      title: "Starfall",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.starfall.com",
    },
    {
      id: 118,
      title: "ABCya",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.abcya.com",
    },
    {
      id: 119,
      title: "SplashLearn",
      type: "Interactive",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.splashlearn.com",
    },
    {
      id: 120,
      title: "BrainPOP",
      type: "Video",
      subject: "General",
      duration: "5-10 min",
      difficulty: "Beginner",
      url: "https://www.brainpop.com",
    },
    {
      id: 121,
      title: "CrashCourse",
      type: "Video",
      subject: "General",
      duration: "10-15 min",
      difficulty: "Intermediate",
      url: "https://youtube.com/@crashcourse",
    },
    {
      id: 122,
      title: "TED Ed",
      type: "Video",
      subject: "General",
      duration: "5-10 min",
      difficulty: "Intermediate",
      url: "https://youtube.com/@TEDEd",
    },
    {
      id: 123,
      title: "SciShow",
      type: "Video",
      subject: "Physics",
      duration: "10-15 min",
      difficulty: "Intermediate",
      url: "https://youtube.com/@scishow",
    },
    {
      id: 124,
      title: "Veritasium",
      type: "Video",
      subject: "Physics",
      duration: "15-20 min",
      difficulty: "Intermediate",
      url: "https://youtube.com/@veritasium",
    },
    {
      id: 125,
      title: "3Blue1Brown",
      type: "Video",
      subject: "Mathematics",
      duration: "15-25 min",
      difficulty: "Advanced",
      url: "https://youtube.com/@3blue1brown",
    },
    {
      id: 126,
      title: "MinutePhysics",
      type: "Video",
      subject: "Physics",
      duration: "5-10 min",
      difficulty: "Intermediate",
      url: "https://youtube.com/@minutephysics",
    },
    {
      id: 127,
      title: "Numberphile",
      type: "Video",
      subject: "Mathematics",
      duration: "10-20 min",
      difficulty: "Intermediate",
      url: "https://youtube.com/@numberphile",
    },
    {
      id: 128,
      title: "CGP Grey",
      type: "Video",
      subject: "General",
      duration: "10-20 min",
      difficulty: "Beginner",
      url: "https://youtube.com/@cgpgrey",
    },
    {
      id: 129,
      title: "Kurzgesagt",
      type: "Video",
      subject: "General",
      duration: "10-15 min",
      difficulty: "Beginner",
      url: "https://youtube.com/@kurzgesagt",
    },
    {
      id: 130,
      title: "AsapSCIENCE",
      type: "Video",
      subject: "Biology",
      duration: "5-10 min",
      difficulty: "Beginner",
      url: "https://youtube.com/@AsapSCIENCE",
    },
    {
      id: 131,
      title: "freeCodeCamp",
      type: "Course",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.freecodecamp.org",
    },
    {
      id: 132,
      title: "Codecademy",
      type: "Interactive",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.codecademy.com",
    },
    {
      id: 133,
      title: "The Odin Project",
      type: "Course",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.theodinproject.com",
    },
    {
      id: 134,
      title: "W3Schools",
      type: "Article",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.w3schools.com",
    },
    {
      id: 135,
      title: "SoloLearn",
      type: "Interactive",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.sololearn.com",
    },
    {
      id: 136,
      title: "Codewars",
      type: "Interactive",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.codewars.com",
    },
    {
      id: 137,
      title: "LeetCode",
      type: "Interactive",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Advanced",
      url: "https://leetcode.com",
    },
    {
      id: 138,
      title: "GeeksforGeeks",
      type: "Article",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.geeksforgeeks.org",
    },
    {
      id: 139,
      title: "Google Digital Garage",
      type: "Course",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://learndigital.withgoogle.com",
    },
    {
      id: 140,
      title: "IBM SkillsBuild",
      type: "Course",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://skillsbuild.org",
    },
    {
      id: 141,
      title: "PhET Simulations",
      type: "Interactive",
      subject: "Physics",
      duration: "30 min",
      difficulty: "Beginner",
      url: "https://phet.colorado.edu",
    },
    {
      id: 142,
      title: "Desmos Calculator",
      type: "Interactive",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.desmos.com",
    },
    {
      id: 143,
      title: "GeoGebra",
      type: "Interactive",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.geogebra.org",
    },
    {
      id: 144,
      title: "Wolfram Alpha",
      type: "Interactive",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Advanced",
      url: "https://www.wolframalpha.com",
    },
    {
      id: 145,
      title: "NASA for Students",
      type: "Article",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.nasa.gov/stem",
    },
    {
      id: 146,
      title: "NASA Climate Kids",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://climatekids.nasa.gov",
    },
    {
      id: 147,
      title: "Exploratorium",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.exploratorium.edu",
    },
    {
      id: 148,
      title: "Mathigon",
      type: "Interactive",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://mathigon.org",
    },
    {
      id: 149,
      title: "NRICH Maths",
      type: "Article",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://nrich.maths.org",
    },
    {
      id: 150,
      title: "Illuminations NCTM",
      type: "Interactive",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://illuminations.nctm.org",
    },
    {
      id: 151,
      title: "Project Gutenberg",
      type: "Document",
      subject: "English",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.gutenberg.org",
    },
    {
      id: 152,
      title: "Open Library",
      type: "Document",
      subject: "English",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://openlibrary.org",
    },
    {
      id: 153,
      title: "Internet Archive",
      type: "Document",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://archive.org",
    },
    {
      id: 154,
      title: "OpenStax",
      type: "Document",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://openstax.org",
    },
    {
      id: 155,
      title: "LibriVox",
      type: "Video",
      subject: "English",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://librivox.org",
    },
    {
      id: 156,
      title: "Storyline Online",
      type: "Video",
      subject: "English",
      duration: "15-30 min",
      difficulty: "Beginner",
      url: "https://www.storylineonline.net",
    },
    {
      id: 157,
      title: "ManyBooks",
      type: "Document",
      subject: "English",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://manybooks.net",
    },
    {
      id: 158,
      title: "Google Books",
      type: "Document",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://books.google.com",
    },
    {
      id: 159,
      title: "Poetry Foundation",
      type: "Article",
      subject: "English",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.poetryfoundation.org",
    },
    {
      id: 160,
      title: "ReadWorks",
      type: "Article",
      subject: "English",
      duration: "20-30 min",
      difficulty: "Beginner",
      url: "https://www.readworks.org",
    },

    // Language Learning
    {
      id: 161,
      title: "Duolingo",
      type: "Interactive",
      subject: "General",
      duration: "5-15 min",
      difficulty: "Beginner",
      url: "https://www.duolingo.com",
    },
    {
      id: 162,
      title: "Memrise",
      type: "Interactive",
      subject: "General",
      duration: "10-20 min",
      difficulty: "Beginner",
      url: "https://www.memrise.com",
    },
    {
      id: 163,
      title: "BBC Languages",
      type: "Article",
      subject: "General",
      duration: "15-30 min",
      difficulty: "Beginner",
      url: "https://www.bbc.co.uk/languages",
    },
    {
      id: 164,
      title: "Busuu",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.busuu.com",
    },
    {
      id: 165,
      title: "LingQ",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.lingq.com",
    },
    {
      id: 166,
      title: "Clozemaster",
      type: "Interactive",
      subject: "General",
      duration: "15-30 min",
      difficulty: "Intermediate",
      url: "https://www.clozemaster.com",
    },
    {
      id: 167,
      title: "Language Transfer",
      type: "Audio",
      subject: "General",
      duration: "30 min",
      difficulty: "Beginner",
      url: "https://www.languagetransfer.org",
    },
    {
      id: 168,
      title: "LyricsTraining",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://lyricstraining.com",
    },
    {
      id: 169,
      title: "HelloTalk",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.hellotalk.com",
    },
    {
      id: 170,
      title: "Forvo",
      type: "Interactive",
      subject: "General",
      duration: "5-10 min",
      difficulty: "Beginner",
      url: "https://forvo.com",
    },
    {
      id: 171,
      title: "Quizlet",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://quizlet.com",
    },
    {
      id: 172,
      title: "Anki",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://apps.ankiweb.net",
    },
    {
      id: 173,
      title: "Notion",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.notion.so",
    },
    {
      id: 174,
      title: "Trello",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://trello.com",
    },
    {
      id: 175,
      title: "Google Classroom",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://classroom.google.com",
    },
    {
      id: 176,
      title: "Canva",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.canva.com",
    },
    {
      id: 177,
      title: "Grammarly",
      type: "Interactive",
      subject: "English",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.grammarly.com",
    },
    {
      id: 178,
      title: "Zotero",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.zotero.org",
    },
    {
      id: 179,
      title: "Mendeley",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.mendeley.com",
    },
    {
      id: 180,
      title: "Forest App",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.forestapp.cc",
    },
    {
      id: 181,
      title: "Brilliant",
      type: "Interactive",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Advanced",
      url: "https://brilliant.org",
    },
    {
      id: 182,
      title: "Art of Problem Solving",
      type: "Course",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Advanced",
      url: "https://artofproblemsolving.com",
    },
    {
      id: 183,
      title: "IXL",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.ixl.com",
    },
    {
      id: 184,
      title: "Toppr",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.toppr.com",
    },
    {
      id: 185,
      title: "Unacademy",
      type: "Video",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://unacademy.com",
    },
    {
      id: 186,
      title: "ExamFear",
      type: "Video",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.examfear.com",
    },
    {
      id: 187,
      title: "StudyPug",
      type: "Video",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.studypug.com",
    },
    {
      id: 188,
      title: "PrepScholar",
      type: "Article",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.prepscholar.com",
    },
    {
      id: 189,
      title: "Varsity Tutors",
      type: "Video",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.varsitytutors.com",
    },
    {
      id: 190,
      title: "Mathway",
      type: "Interactive",
      subject: "Mathematics",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.mathway.com",
    },
    {
      id: 191,
      title: "Skillshare",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.skillshare.com",
    },
    {
      id: 192,
      title: "Adobe Education Exchange",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://edex.adobe.com",
    },
    {
      id: 193,
      title: "Inkscape Tutorials",
      type: "Article",
      subject: "General",
      duration: "30-60 min",
      difficulty: "Beginner",
      url: "https://inkscape.org/learn",
    },
    {
      id: 194,
      title: "Pixlr",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://pixlr.com",
    },
    {
      id: 195,
      title: "Scratch",
      type: "Interactive",
      subject: "Computer Science",
      duration: "30-60 min",
      difficulty: "Beginner",
      url: "https://scratch.mit.edu",
    },
    {
      id: 196,
      title: "Tynker",
      type: "Interactive",
      subject: "Computer Science",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.tynker.com",
    },
    {
      id: 197,
      title: "Drawspace",
      type: "Course",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.drawspace.com",
    },
    {
      id: 198,
      title: "MusicTheory.net",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.musictheory.net",
    },
    {
      id: 199,
      title: "Teoria",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Intermediate",
      url: "https://www.teoria.com",
    },
    {
      id: 200,
      title: "LightNote",
      type: "Interactive",
      subject: "General",
      duration: "Varies",
      difficulty: "Beginner",
      url: "https://www.lightnote.co",
    },
  ];

  const filteredResources = useMemo(() => {
    return resources.filter((resource) => {
      const matchesSearch =
        resource.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        resource.subject.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesType =
        selectedType === 'All Types' || resource.type === selectedType;
      const matchesLevel =
        selectedLevel === 'All Levels' || resource.difficulty === selectedLevel;

      return matchesSearch && matchesType && matchesLevel;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchTerm, selectedType, selectedLevel]);

  return (
    <main className="flex-1">
      <section className="py-16 md:py-24 bg-white">
        <div className="container mx-auto px-4">
          <div className="mx-auto mb-16 max-w-3xl">
            <h1 className="text-5xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <FiBook className="text-amber-600" /> Resource Curator
            </h1>
            <p className="text-lg text-gray-600">
              Discover AI-powered learning resources tailored to your needs.
            </p>
          </div>

          <div className="mb-8 grid gap-4 md:grid-cols-4">
            <input
              type="text"
              placeholder="Search resources..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="md:col-span-2 border border-gray-200 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-amber-700"
            />
            <select
              value={selectedType}
              onChange={(e) => setSelectedType(e.target.value)}
              className="border border-gray-200 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-amber-700"
            >
              <option>All Types</option>
              <option>Video</option>
              <option>Article</option>
              <option>Interactive</option>
            </select>
            <select
              value={selectedLevel}
              onChange={(e) => setSelectedLevel(e.target.value)}
              className="border border-gray-200 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-amber-700"
            >
              <option>All Levels</option>
              <option>Beginner</option>
              <option>Intermediate</option>
              <option>Advanced</option>
            </select>
          </div>

          <div className="grid gap-6 md:grid-cols-2">
            {filteredResources.map((resource) => (
              <div
                key={resource.id}
                className="rounded-2xl border border-gray-200 bg-white p-6 shadow-lg hover:shadow-xl transition-all"
              >
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h3 className="text-xl font-semibold text-gray-900">
                      {resource.title}
                    </h3>
                    <p className="text-amber-700 text-sm mt-1">
                      {resource.subject}
                    </p>
                  </div>
                  <span className="px-3 py-1 bg-amber-100 text-amber-700 rounded-full text-xs font-semibold">
                    {resource.type}
                  </span>
                </div>

                <div className="space-y-2 mb-4">
                  <p className="text-gray-600 text-sm">
                    <LuAlarmClock className="inline mr-1 text-amber-600" /> Duration: {resource.duration}
                  </p>
                  <p className="text-gray-600 text-sm">
                    <FiBarChart2 className="inline mr-1 text-amber-600" /> Level: {resource.difficulty}
                  </p>
                </div>

                {resource.url ? (
                  <a
                    href={resource.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="block w-full py-2 bg-amber-700 text-white font-semibold rounded-lg hover:bg-amber-800 transition-all text-center"
                  >
                    <FaDownload className="inline mr-1" /> Open Resource
                  </a>
                ) : (
                  <button className="w-full py-2 bg-amber-700 text-white font-semibold rounded-lg hover:bg-amber-800 transition-all">
                    <FaDownload className="inline mr-1" /> Open Resource
                  </button>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
